packit: tweak the RPM version string
git describe returns in systemd's case 'v245-xxx' which breaks RPM
version detection (that expects 245-xxxx'. Let's tweak the version string
accordingly

Using the default one leads to this outcome:
```
dnf install ...
...
Error: Problem: The operation would result in removing the following protected packages: kernel-core, system
```